# Generated by Django 6.1 on 2026-08-17 17:53

import api.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(default='General Inquiry', max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentRecord',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('environment_name', models.CharField(max_length=255)),
                ('provider', models.CharField(default='AWS', max_length=100)),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=12280.0, max_digits=12)),
                ('specs', models.JSONField(default=dict)),
                ('region', models.CharField(default='Asia Pacific (Mumbai)', max_length=100)),
                ('status', models.CharField(default='deployed', max_length=50)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('endpoint_url', models.CharField(blank=True, max_length=255, null=True)),
                ('logs', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstimationRecord',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('app_type', models.CharField(default='Microservices & Web APIs', max_length=255)),
                ('vcpu', models.IntegerField(default=8)),
                ('ram', models.IntegerField(default=32)),
                ('storage', models.IntegerField(default=500)),
                ('traffic', models.CharField(default='1,000,000 req/day', max_length=255)),
                ('region', models.CharField(default='Gujarat (GIFT City / Gandhinagar)', max_length=255)),
                ('performance_tier', models.CharField(default='High Performance', max_length=255)),
                ('budget_tier', models.CharField(default='Balanced', max_length=255)),
                ('calculated_result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaitlistSubscriber',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('source', models.CharField(default='home_page', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('company', models.CharField(default='CloudWise Enterprise', max_length=255)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer'), ('admin', 'Admin')], default='owner', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('user_id_str', models.CharField(default='default_user', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='Cloud deployment advisory project')),
                ('environment', models.CharField(default='Production', max_length=100)),
                ('user_role', models.CharField(default='owner', max_length=50)),
                ('current_step', models.CharField(default='estimation', max_length=50)),
                ('estimation', models.JSONField(default=api.models.default_estimation)),
                ('selected_recommendation', models.JSONField(default=api.models.default_recommendation)),
                ('github_repo', models.JSONField(blank=True, null=True)),
                ('deployment', models.JSONField(default=api.models.default_deployment)),
                ('optimizations', models.JSONField(default=api.models.default_optimizations)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
