# Generated by Django 6.1.1 on 2026-09-18 05:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_githubconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=50)),
                ('service', models.CharField(max_length=100)),
                ('region', models.CharField(db_index=True, max_length=100)),
                ('sku', models.CharField(blank=True, default='', max_length=255)),
                ('instanceType', models.CharField(db_index=True, max_length=100)),
                ('vcpu', models.IntegerField()),
                ('memoryGiB', models.FloatField()),
                ('storageType', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(default='Hrs', max_length=50)),
                ('pricePerUnit', models.FloatField(db_index=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('pricingModel', models.CharField(default='OnDemand', max_length=50)),
                ('fetchedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['pricePerUnit'],
                'unique_together': {('provider', 'instanceType', 'region')},
            },
        ),
    ]
