# Generated by Django 6.1.1 on 2026-09-19 16:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_githubconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deployment',
            field=models.JSONField(blank=True, default=api.models.default_deployment, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='optimizations',
            field=models.JSONField(blank=True, default=api.models.default_optimizations, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='selected_recommendation',
            field=models.JSONField(blank=True, default=api.models.default_recommendation, null=True),
        ),
    ]
