# Generated by Django 6.1.1 on 2026-09-23 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pricesnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id_str', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('cost_usd', models.FloatField()),
                ('cpu_percent', models.FloatField(default=0.0)),
                ('ram_percent', models.FloatField(default=0.0)),
                ('storage_percent', models.FloatField(default=0.0)),
                ('requests_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_history', to='api.project')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('project_id_str', 'date')},
            },
        ),
    ]
