# Generated by Django 6.1.1 on 2026-09-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_deployment_alter_project_optimizations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentrecord',
            name='provider_deployment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deploymentrecord',
            name='provider_project_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
