# Generated by Django 6.1.1 on 2026-09-23 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_provider_ids_to_deployment_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployment_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AWSConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_arn', models.CharField(max_length=255)),
                ('external_id', models.CharField(max_length=128)),
                ('account_id', models.CharField(blank=True, default='', max_length=64)),
                ('region', models.CharField(default='ap-south-1', max_length=50)),
                ('status', models.CharField(default='active', max_length=30)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aws_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EC2Instance',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('instance_id', models.CharField(max_length=64, unique=True)),
                ('region', models.CharField(default='ap-south-1', max_length=50)),
                ('instance_type', models.CharField(default='t3.micro', max_length=50)),
                ('ami_id', models.CharField(blank=True, default='', max_length=64)),
                ('public_ip', models.CharField(blank=True, default='', max_length=64)),
                ('private_ip', models.CharField(blank=True, default='', max_length=64)),
                ('security_group_id', models.CharField(blank=True, default='', max_length=64)),
                ('security_group_name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('environment_name', models.CharField(blank=True, default='', max_length=255)),
                ('docker_installed', models.BooleanField(default=False)),
                ('deployment_count', models.IntegerField(default=1)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ec2_instances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
