# Generated by Django 6.0.2 on 2026-09-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_provider_ids_to_deployment_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudPricingCache',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('instance_type', models.CharField(max_length=100)),
                ('region', models.CharField(default='Asia Pacific (Mumbai)', max_length=100)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hourly_usd', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('specs', models.JSONField(default=dict)),
                ('source', models.CharField(default='API', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'instance_type', 'region'], name='api_cloudpr_provide_3c7ef7_idx')],
                'unique_together': {('provider', 'instance_type', 'region')},
            },
        ),
    ]
