# Generated by Django 6.1.1 on 2026-09-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_deploymentrecord_user_awsconnection_ec2instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubconnection',
            name='scopes',
            field=models.CharField(blank=True, default='repo,workflow', max_length=255),
        ),
        migrations.AddField(
            model_name='githubconnection',
            name='status',
            field=models.CharField(blank=True, default='connected', max_length=50),
        ),
        migrations.AlterField(
            model_name='githubconnection',
            name='github_login',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='githubconnection',
            name='github_user_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
