# Generated by Django 6.0.2 on 2026-09-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cloudpricingcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudpricingcache',
            name='estimated',
            field=models.BooleanField(default=False),
        ),
    ]
