# Generated by Django 6.1.1 on 2026-09-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_deployment_record_ownership_and_pipeline_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentrecord',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deploymentrecord',
            name='current_stage',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='deploymentrecord',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deploymentrecord',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='deploymentrecord',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deploymentrecord',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deploymentrecord',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deploymentrecord',
            name='status_message',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
