# Generated by Django 6.1.1 on 2026-09-29 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_deploymentrecord_cancel_requested_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MongoDBAtlasConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret_encrypted', models.TextField()),
                ('project_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='connected', max_length=50)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atlas_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
