# Generated by Django 6.1.1 on 2026-10-06 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_costdatapoint'),
        ('api', '0009_mongodbatlasconnection'),
    ]

    operations = [
    ]
