import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  FileCode, 
  Github, 
  Download, 
  Copy, 
  Check, 
  ArrowRight, 
  Sparkles, 
  Terminal, 
  ShieldCheck, 
  X, 
  RefreshCw,
  GitBranch,
  Layers,
  Code
} from 'lucide-react';
import { useCloudWise, formatINR } from '@/context/CloudWiseContext';

export const GenerateFiles: React.FC = () => {
  const navigate = useNavigate();
  const { 
    estimation, 
    selectedRecommendation, 
    githubRepo, 
    connectGitHub, 
    updateActiveProject,
    showToast,
    activeProject
  } = useCloudWise();

  const [activeTab, setActiveTab] = useState<'dockerfile' | 'cicd' | 'compose'>('dockerfile');
  const [copied, setCopied] = useState(false);
  const [showGithubModal, setShowGithubModal] = useState(false);
  const [repoInput, setRepoInput] = useState(githubRepo?.name || 'acme-org/cloudwise-workload');
  const [connecting, setConnecting] = useState(false);
  const [syncedStatus, setSyncedStatus] = useState(githubRepo?.synced || false);

  const providerName = selectedRecommendation.provider;
  const appType = estimation.appType;

  // Generate dynamic Dockerfile based on workload
  const dockerfileSnippet = `# Auto-generated by CloudWise Resource Intelligence Engine
# Workload: ${appType}
# Target Cloud: ${providerName} (${selectedRecommendation.title})

FROM node:20-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci --only=production

# Copy application source code
COPY . .

# Build application bundle
RUN npm run build || echo "No custom build script specified"

# Production Stage
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
ENV TARGET_CLOUD=${providerName.toUpperCase()}
ENV VCPU_ALLOCATION=${estimation.vcpu}
ENV RAM_ALLOCATION_GB=${estimation.ram}

# Create non-root system user for security hardening
RUN addgroup --system --gid 1001 nodejs && \\
    adduser --system --uid 1001 appuser

COPY --from=builder /app ./

USER appuser
EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
  CMD wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1

CMD ["npm", "start"]
`;

  // Generate dynamic CI/CD Pipeline YAML based on provider
  const getCicdSnippet = () => {
    switch (providerName) {
      case 'AWS':
        return `# AWS ECS / EKS Automated CI/CD Deployment Pipeline
name: Deploy CloudWise Workload to AWS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ${estimation.region.includes('Gujarat') ? 'ap-south-1' : 'ap-south-1'}
  ECR_REPOSITORY: cloudwise-${estimation.appType.toLowerCase().replace(/[^a-z0-9]/g, '-')}
  ECS_SERVICE: cloudwise-prod-service
  ECS_CLUSTER: ${selectedRecommendation.title.toLowerCase().replace(/[^a-z0-9]/g, '-')}

jobs:
  deploy:
    name: Build & Push Container to AWS ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: \${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker Image
        env:
          ECR_REGISTRY: \${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: \${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Deploy Task Definition to Amazon ECS
        run: |
          echo "Successfully provisioned container node: ${selectedRecommendation.specs.vcpu} vCPU / ${selectedRecommendation.specs.ram}GB RAM"
`;
      case 'GCP':
        return `# Google Cloud Run / GKE Deployment Pipeline
name: Deploy CloudWise Workload to GCP

on:
  push:
    branches: [ "main" ]

env:
  GCP_PROJECT_ID: \${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: cloudwise-app
  REGION: asia-south1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '\${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Deploy to Cloud Run
        run: |
          gcloud builds submit --tag gcr.io/\$GCP_PROJECT_ID/\$SERVICE_NAME:\${{ github.sha }}
          gcloud run deploy \$SERVICE_NAME --image gcr.io/\$GCP_PROJECT_ID/\$SERVICE_NAME:\${{ github.sha }} --platform managed --region \$REGION --cpu ${selectedRecommendation.specs.vcpu} --memory ${selectedRecommendation.specs.ram}Gi
`;
      case 'Azure':
        return `# Azure App Service / AKS Deployment Pipeline
name: Deploy CloudWise Workload to Azure

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: \${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Docker Image to Azure Container Registry
        run: |
          az acr build --registry cloudwiseacr --image cloudwise-app:\${{ github.sha }} .

      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cloudwise-prod-app'
          images: 'cloudwiseacr.azurecr.io/cloudwise-app:\${{ github.sha }}'
`;
      default:
        return `# DigitalOcean App Platform Automated Deployment
name: Deploy CloudWise Workload to DigitalOcean

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: DigitalOcean App Platform Trigger
        uses: digitalocean/app-deploy-action@v2
        with:
          token: \${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
`;
    }
  };

  const cicdSnippet = getCicdSnippet();

  const composeSnippet = `# Local & Multi-Node Orchestration Configuration
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VCPU_LIMIT=${estimation.vcpu}
      - RAM_LIMIT=${estimation.ram}G
    deploy:
      resources:
        limits:
          cpus: '${estimation.vcpu}'
          memory: ${estimation.ram}G
        reservations:
          cpus: '${Math.max(1, Math.floor(estimation.vcpu / 2))}'
          memory: ${Math.floor(estimation.ram / 2)}G
    restart: always
`;

  const getActiveCode = () => {
    switch (activeTab) {
      case 'dockerfile':
        return dockerfileSnippet;
      case 'cicd':
        return cicdSnippet;
      case 'compose':
        return composeSnippet;
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getActiveCode());
    setCopied(true);
    showToast('Snippet copied to clipboard!', 'success');
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const filenames: Record<string, string> = {
      dockerfile: 'Dockerfile',
      cicd: 'deploy.yml',
      compose: 'docker-compose.yml'
    };
    const content = getActiveCode();
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filenames[activeTab];
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    showToast(`Downloaded ${filenames[activeTab]}`, 'success');
  };

  const handleConnectSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!repoInput.trim()) return;

    setConnecting(true);
    const success = await connectGitHub(repoInput.trim());
    setConnecting(false);

    if (success) {
      setShowGithubModal(false);
      setSyncedStatus(true);
    }
  };

  const handleProceedToDeployment = () => {
    updateActiveProject({ currentStep: 'deployment' });
    navigate('/deployment');
  };

  return (
    <div className="min-h-screen max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-10">
      
      {/* Header */}
      <div className="text-center space-y-3 max-w-3xl mx-auto">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-violet-500/10 border border-violet-500/30 text-violet-300 text-xs font-semibold">
          <FileCode className="w-3.5 h-3.5" />
          <span>Step 3: Infrastructure Code & GitHub Sync</span>
        </div>
        <h1 className="text-3xl sm:text-5xl font-extrabold text-white">
          Generate Deployment Files
        </h1>
        <p className="text-slate-400 text-sm sm:text-base leading-relaxed">
          Auto-generate production Dockerfiles and CI/CD pipelines tailored to your workload profile ({estimation.appType}) and selected cloud ({selectedRecommendation.provider}).
        </p>
      </div>

      {/* GitHub Integration Banner */}
      <div className="glass-panel p-6 rounded-3xl border border-violet-500/30 bg-violet-950/10 flex flex-col md:flex-row items-center justify-between gap-6">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-2xl bg-slate-900 border border-slate-700 flex items-center justify-center text-white shrink-0">
            <Github size={24} />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-lg font-bold text-white">GitHub Repository Sync</h3>
              {syncedStatus ? (
                <span className="px-2.5 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 text-xs font-bold border border-emerald-500/40 flex items-center gap-1">
                  <ShieldCheck size={12} /> Connected
                </span>
              ) : (
                <span className="px-2.5 py-0.5 rounded-full bg-amber-500/20 text-amber-300 text-xs font-bold border border-amber-500/40">
                  Not Linked
                </span>
              )}
            </div>
            <p className="text-xs text-slate-400 pt-0.5">
              {syncedStatus 
                ? `Linked to repository: ${githubRepo?.name || repoInput} (Generated files synced)`
                : 'Link your GitHub repository to automatically commit generated Docker & CI/CD pipeline files.'}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={() => setShowGithubModal(true)}
            className="px-6 py-3 rounded-xl bg-slate-900 hover:bg-slate-800 border border-slate-700 text-white font-bold text-xs transition-colors flex items-center gap-2"
          >
            <Github size={16} />
            <span>{syncedStatus ? 'Manage GitHub Sync' : 'Connect GitHub Repo'}</span>
          </button>
        </div>
      </div>

      {/* Tabbed Code File Viewer */}
      <div className="glass-panel rounded-3xl border border-slate-800 overflow-hidden space-y-0">
        
        {/* Tab Headers & Actions */}
        <div className="bg-slate-900/90 px-6 py-4 border-b border-slate-800 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          
          {/* Tabs */}
          <div className="flex bg-slate-950 p-1 rounded-2xl border border-slate-800 text-xs font-semibold">
            <button
              onClick={() => setActiveTab('dockerfile')}
              className={`px-4 py-2 rounded-xl transition-all flex items-center gap-2 ${
                activeTab === 'dockerfile'
                  ? 'bg-cyan-500 text-slate-950 font-bold shadow-md shadow-cyan-500/20'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              <Code size={14} />
              <span>Dockerfile</span>
            </button>

            <button
              onClick={() => setActiveTab('cicd')}
              className={`px-4 py-2 rounded-xl transition-all flex items-center gap-2 ${
                activeTab === 'cicd'
                  ? 'bg-cyan-500 text-slate-950 font-bold shadow-md shadow-cyan-500/20'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              <GitBranch size={14} />
              <span>CI/CD ({providerName} Pipeline)</span>
            </button>

            <button
              onClick={() => setActiveTab('compose')}
              className={`px-4 py-2 rounded-xl transition-all flex items-center gap-2 ${
                activeTab === 'compose'
                  ? 'bg-cyan-500 text-slate-950 font-bold shadow-md shadow-cyan-500/20'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              <Layers size={14} />
              <span>docker-compose.yml</span>
            </button>
          </div>

          {/* Utility Buttons */}
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="px-3.5 py-2 rounded-xl bg-slate-900 hover:bg-slate-800 border border-slate-700 text-slate-300 font-semibold text-xs transition-colors flex items-center gap-1.5"
            >
              {copied ? <Check size={14} className="text-emerald-400" /> : <Copy size={14} />}
              <span>{copied ? 'Copied!' : 'Copy Code'}</span>
            </button>

            <button
              onClick={handleDownload}
              className="px-3.5 py-2 rounded-xl bg-cyan-500/10 hover:bg-cyan-500/20 border border-cyan-500/30 text-cyan-300 font-semibold text-xs transition-colors flex items-center gap-1.5"
            >
              <Download size={14} />
              <span>Download File</span>
            </button>
          </div>

        </div>

        {/* Code Content Container */}
        <div className="p-6 bg-slate-950 font-mono text-xs text-slate-300 leading-relaxed overflow-x-auto min-h-[380px] max-h-[500px]">
          <pre className="text-slate-200">
            <code>{getActiveCode()}</code>
          </pre>
        </div>

      </div>

      {/* Next Step Action Bar */}
      <div className="glass-panel p-6 rounded-3xl text-center space-y-4 max-w-xl mx-auto border border-cyan-500/20">
        <h4 className="text-base font-bold text-white">Ready to Provision Cloud Environment?</h4>
        <p className="text-xs text-slate-400">
          Generated artifacts ready. Proceed to launch automated provisioning on <strong className="text-cyan-300">{providerName}</strong> ({selectedRecommendation.title}).
        </p>
        <button
          onClick={handleProceedToDeployment}
          className="w-full py-4 rounded-xl bg-gradient-to-r from-cyan-400 via-cyan-500 to-blue-600 hover:from-cyan-300 hover:to-blue-500 text-slate-950 font-bold text-sm transition-all shadow-xl shadow-cyan-500/20 flex items-center justify-center gap-2 group active:scale-98"
        >
          <span>Proceed to Provisioning & Deployment</span>
          <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
        </button>
      </div>

      {/* Connect GitHub OAuth Modal */}
      <AnimatePresence>
        {showGithubModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="glass-panel max-w-md w-full p-6 sm:p-8 rounded-3xl space-y-6 border border-slate-700 shadow-2xl relative"
            >
              <button
                onClick={() => setShowGithubModal(false)}
                className="absolute top-5 right-5 text-slate-400 hover:text-white p-1 rounded-lg bg-slate-900 border border-slate-800"
              >
                <X size={18} />
              </button>

              <div className="space-y-1">
                <div className="w-10 h-10 rounded-xl bg-slate-900 border border-slate-700 flex items-center justify-center text-white mb-2">
                  <Github size={20} />
                </div>
                <h3 className="text-xl font-extrabold text-white">Connect GitHub Repository</h3>
                <p className="text-xs text-slate-400">
                  Authenticate via GitHub OAuth to push Dockerfile and CI/CD workflow directly to your repository's <code className="text-cyan-300">main</code> branch.
                </p>
              </div>

              <form onSubmit={handleConnectSubmit} className="space-y-4">
                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-slate-300">Target Repository (org/repo)</label>
                  <input
                    type="text"
                    required
                    placeholder="e.g. acme-org/payment-service"
                    value={repoInput}
                    onChange={(e) => setRepoInput(e.target.value)}
                    className="w-full bg-slate-900 border border-slate-700/80 rounded-xl px-4 py-3 text-xs text-white focus:outline-none focus:border-cyan-400"
                  />
                </div>

                <div className="p-3 rounded-xl bg-slate-900 border border-slate-800 text-[11px] text-slate-400 space-y-1">
                  <div className="flex justify-between">
                    <span>OAuth Permission Scope:</span>
                    <span className="text-cyan-300 font-mono">repo:write, workflow</span>
                  </div>
                  <div className="flex justify-between">
                    <span>Target Branch:</span>
                    <span className="text-emerald-400 font-bold">main</span>
                  </div>
                </div>

                <div className="pt-2 flex gap-3">
                  <button
                    type="submit"
                    disabled={connecting}
                    className="flex-1 py-3.5 rounded-xl bg-gradient-to-r from-violet-500 to-indigo-600 hover:from-violet-400 hover:to-indigo-500 text-white font-bold text-xs transition-all shadow-lg shadow-violet-500/20 flex items-center justify-center gap-2 active:scale-98 disabled:opacity-50"
                  >
                    {connecting ? <RefreshCw size={16} className="animate-spin" /> : <Github size={16} />}
                    <span>{connecting ? 'Authenticating...' : 'Connect & Push Files'}</span>
                  </button>
                  <button
                    type="button"
                    onClick={() => setShowGithubModal(false)}
                    className="px-4 py-3.5 rounded-xl bg-slate-900 border border-slate-800 text-slate-300 font-semibold text-xs hover:bg-slate-800"
                  >
                    Cancel
                  </button>
                </div>
              </form>

            </motion.div>
          </div>
        )}
      </AnimatePresence>

    </div>
  );
};
